### PR TITLE
fix: use `Current.area.h` instead of `#SINGLE_KEYS` to avoid the candidate list being cut off

### PR DESCRIPTION
**Pull request by sxyazi**

### CODE REVIEW

**Comment by DreamMaoMao** [comment]
image

Folder names containing spaces will still cause errors

**Comment by sxyazi** [comment]
Have you used the latest code from this PR?

**Comment by DreamMaoMao** [comment]
> Have you used the latest code from this PR?您是否使用了此PR的最新代码？

image


yes, it only fix filename with space.  but doesn't work with foldername with space

**Comment by sxyazi** [comment]
https://github.com/DreamMaoMao/keyjump.yazi/assets/17523360/77a8e30d-70d4-47ee-a079-788d468cf379

I can't reproduce it on my side...

**Comment by DreamMaoMao** [comment]
It seems that this issue has nothing to do with this PR. Let’s go back to the this issue https://github.com/DreamMaoMao/keyjump.yazi/issues/6  to discuss this.

**Comment by DreamMaoMao** [comment]
There is no problem with this PR ,lgtm

**Pull request merged**
