### PR TITLE
refactor: use parameter `state` instead of global variable

### PR DESCRIPTION
**Pull request by sxyazi**
See https://github.com/sxyazi/yazi/pull/710

### CODE REVIEW

**Comment by DreamMaoMao** [comment]
image
image


it seems to not work correctly

**Comment by sxyazi** [comment]
Have you used the plugin code from this PR?

**Comment by DreamMaoMao** [comment]
oh!It seems that I copied the wrong file, now the test seems to be fine

**Comment by DreamMaoMao** [comment]
oh no ,there are other problem in this pr:(
image

**Pull request merged**
